### PR TITLE
thumby: add board defs for display and buttons

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is to try to add support for the Thumby.

### CODE REVIEW

**Comment by aykevl** [comment]
Can you also add the board to tinygo_test.go?
Otherwise looks good to me. It would be nice to allow the display to sleep (I didn't check whether the display supports this) but that can happen at a later time.

Also there's some code duplication with other board files but that can be fixed in a separate PR.

**Comment by aykevl** [comment]
Uh, and I think I need to set up CI for this repository.

**Comment by deadprogram** [comment]
The PR to `drivers` repo https://github.com/tinygo-org/drivers/pull/671 will be needed to complete this PR.

**Comment by deadprogram** [comment]
The PR to drivers was merged @aykevl so this PR is now ready.

**Pull request merged**
